version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: pingomon-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  clickhouse:
    image: clickhouse/clickhouse-server:25.10-alpine
    container_name: pingomon-clickhouse
    env_file:
      - .env
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB_NAME}
      CLICKHOUSE_USER: ${CLICKHOUSE_ROOT_USER_NAME}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_ROOT_USER_PASSWORD}
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # Native
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1'"]
      interval: 5s
      timeout: 3s
      retries: 60
    restart: unless-stopped

  worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: worker
    container_name: pingomon-worker
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

  bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: bot
    container_name: pingomon-bot
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

  notification_worker:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      target: notifier
    container_name: pingomon-notifier
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

volumes:
  ch_data:
  pg_data:
